In [84]:
!pip install pandas


In [85]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [86]:
  #Importing Library
import numpy as np
import pandas as pd
import random

In [87]:
# Dataset from importing
movie = pd.read_csv('/content/drive/MyDrive/movies.csv')

In [88]:
movie.head()

MOVIES         YEAR  \
0                        Blood Red Sky       (2021)   
1  Masters of the Universe: Revelation     (2021– )   
2                     The Walking Dead  (2010–2022)   
3                       Rick and Morty     (2013– )   
4                      Army of Thieves       (2021)   

                                        GENRE  RATING  \
0      \nAction, Horror, Thriller                 6.1   
1  \nAnimation, Action, Adventure                 5.0   
2       \nDrama, Horror, Thriller                 8.2   
3  \nAnimation, Adventure, Comedy                 9.2   
4         \nAction, Crime, Horror                 NaN   

                                            ONE-LINE  \
0  \nA woman with a mysterious illness is forced ...   
1  \nThe war for Eternia begins again in what may...   
2  \nSheriff Deputy Rick Grimes wakes up from a c...   
3  \nAn animated series that follows the exploits...   
4  \nA prequel, set before the events of Army of ...   

                                               STARS    VOTES  RunTime Gross  
0  \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062    121.0   NaN  
1  \n            \n    Stars:\nChris Wood, \nSara...   17,870     25.0   NaN  
2  \n            \n    Stars:\nAndrew Lincoln, \n...  885,805     44.0   NaN  
3  \n            \n    Stars:\nJustin Roiland, \n...  414,849     23.0   NaN  
4  \n    Director:\nMatthias Schweighöfer\n| \n  ...      NaN      NaN   NaN

In [89]:
movie['GENRE']

0           \nAction, Horror, Thriller            
1       \nAnimation, Action, Adventure            
2            \nDrama, Horror, Thriller            
3       \nAnimation, Adventure, Comedy            
4              \nAction, Crime, Horror            
                           ...                    
9994       \nAdventure, Drama, Fantasy            
9995    \nAnimation, Action, Adventure            
9996              \nDocumentary, Sport            
9997       \nAdventure, Drama, Fantasy            
9998       \nAdventure, Drama, Fantasy            
Name: GENRE, Length: 9999, dtype: object

## feature selection
    Movies
    year
    Genre
    Rates
    STars
    Runtime

In [90]:
movie = movie[['MOVIES','YEAR','GENRE','RATING','ONE-LINE','STARS','VOTES','RunTime','Gross']]

#Filling the null value of **RUNTIME**

In [91]:
movie['RunTime']=movie['RunTime'].replace(np.nan, random.choice(['120','80',]))

In [92]:
movie

MOVIES         YEAR  \
0                           Blood Red Sky       (2021)   
1     Masters of the Universe: Revelation     (2021– )   
2                        The Walking Dead  (2010–2022)   
3                          Rick and Morty     (2013– )   
4                         Army of Thieves       (2021)   
...                                   ...          ...   
9994                       The Imperfects     (2021– )   
9995                               Arcane     (2021– )   
9996                    Heart of Invictus     (2022– )   
9997                       The Imperfects     (2021– )   
9998                       The Imperfects     (2021– )   

                                           GENRE  RATING  \
0         \nAction, Horror, Thriller                 6.1   
1     \nAnimation, Action, Adventure                 5.0   
2          \nDrama, Horror, Thriller                 8.2   
3     \nAnimation, Adventure, Comedy                 9.2   
4            \nAction, Crime, Horror                 NaN   
...                                          ...     ...   
9994     \nAdventure, Drama, Fantasy                 NaN   
9995  \nAnimation, Action, Adventure                 NaN   
9996            \nDocumentary, Sport                 NaN   
9997     \nAdventure, Drama, Fantasy                 NaN   
9998     \nAdventure, Drama, Fantasy                 NaN   

                                               ONE-LINE  \
0     \nA woman with a mysterious illness is forced ...   
1     \nThe war for Eternia begins again in what may...   
2     \nSheriff Deputy Rick Grimes wakes up from a c...   
3     \nAn animated series that follows the exploits...   
4     \nA prequel, set before the events of Army of ...   
...                                                 ...   
9994                                     \nAdd a Plot\n   
9995                                     \nAdd a Plot\n   
9996                                     \nAdd a Plot\n   
9997                                     \nAdd a Plot\n   
9998                                     \nAdd a Plot\n   

                                                  STARS    VOTES RunTime Gross  
0     \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062   121.0   NaN  
1     \n            \n    Stars:\nChris Wood, \nSara...   17,870    25.0   NaN  
2     \n            \n    Stars:\nAndrew Lincoln, \n...  885,805    44.0   NaN  
3     \n            \n    Stars:\nJustin Roiland, \n...  414,849    23.0   NaN  
4     \n    Director:\nMatthias Schweighöfer\n| \n  ...      NaN      80   NaN  
...                                                 ...      ...     ...   ...  
9994  \n            \n    Stars:\nMorgan Taylor Camp...      NaN      80   NaN  
9995                                                 \n      NaN      80   NaN  
9996  \n    Director:\nOrlando von Einsiedel\n| \n  ...      NaN      80   NaN  
9997  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      80   NaN  
9998  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      80   NaN  

[9999 rows x 9 columns]

#Assigning random RATES too

In [93]:
movie['RATING']=movie['RATING'].replace(np.nan, random.choice(['5.1','7.2','5.7','6.5']))

In [94]:
movie

MOVIES         YEAR  \
0                           Blood Red Sky       (2021)   
1     Masters of the Universe: Revelation     (2021– )   
2                        The Walking Dead  (2010–2022)   
3                          Rick and Morty     (2013– )   
4                         Army of Thieves       (2021)   
...                                   ...          ...   
9994                       The Imperfects     (2021– )   
9995                               Arcane     (2021– )   
9996                    Heart of Invictus     (2022– )   
9997                       The Imperfects     (2021– )   
9998                       The Imperfects     (2021– )   

                                           GENRE RATING  \
0         \nAction, Horror, Thriller                6.1   
1     \nAnimation, Action, Adventure                5.0   
2          \nDrama, Horror, Thriller                8.2   
3     \nAnimation, Adventure, Comedy                9.2   
4            \nAction, Crime, Horror                7.2   
...                                          ...    ...   
9994     \nAdventure, Drama, Fantasy                7.2   
9995  \nAnimation, Action, Adventure                7.2   
9996            \nDocumentary, Sport                7.2   
9997     \nAdventure, Drama, Fantasy                7.2   
9998     \nAdventure, Drama, Fantasy                7.2   

                                               ONE-LINE  \
0     \nA woman with a mysterious illness is forced ...   
1     \nThe war for Eternia begins again in what may...   
2     \nSheriff Deputy Rick Grimes wakes up from a c...   
3     \nAn animated series that follows the exploits...   
4     \nA prequel, set before the events of Army of ...   
...                                                 ...   
9994                                     \nAdd a Plot\n   
9995                                     \nAdd a Plot\n   
9996                                     \nAdd a Plot\n   
9997                                     \nAdd a Plot\n   
9998                                     \nAdd a Plot\n   

                                                  STARS    VOTES RunTime Gross  
0     \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062   121.0   NaN  
1     \n            \n    Stars:\nChris Wood, \nSara...   17,870    25.0   NaN  
2     \n            \n    Stars:\nAndrew Lincoln, \n...  885,805    44.0   NaN  
3     \n            \n    Stars:\nJustin Roiland, \n...  414,849    23.0   NaN  
4     \n    Director:\nMatthias Schweighöfer\n| \n  ...      NaN      80   NaN  
...                                                 ...      ...     ...   ...  
9994  \n            \n    Stars:\nMorgan Taylor Camp...      NaN      80   NaN  
9995                                                 \n      NaN      80   NaN  
9996  \n    Director:\nOrlando von Einsiedel\n| \n  ...      NaN      80   NaN  
9997  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      80   NaN  
9998  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      80   NaN  

[9999 rows x 9 columns]

# removing **\n** from start of all the GENRES

In [95]:
movie['GENRE'] = movie['GENRE'].str.strip()
movie

MOVIES         YEAR  \
0                           Blood Red Sky       (2021)   
1     Masters of the Universe: Revelation     (2021– )   
2                        The Walking Dead  (2010–2022)   
3                          Rick and Morty     (2013– )   
4                         Army of Thieves       (2021)   
...                                   ...          ...   
9994                       The Imperfects     (2021– )   
9995                               Arcane     (2021– )   
9996                    Heart of Invictus     (2022– )   
9997                       The Imperfects     (2021– )   
9998                       The Imperfects     (2021– )   

                             GENRE RATING  \
0         Action, Horror, Thriller    6.1   
1     Animation, Action, Adventure    5.0   
2          Drama, Horror, Thriller    8.2   
3     Animation, Adventure, Comedy    9.2   
4            Action, Crime, Horror    7.2   
...                            ...    ...   
9994     Adventure, Drama, Fantasy    7.2   
9995  Animation, Action, Adventure    7.2   
9996            Documentary, Sport    7.2   
9997     Adventure, Drama, Fantasy    7.2   
9998     Adventure, Drama, Fantasy    7.2   

                                               ONE-LINE  \
0     \nA woman with a mysterious illness is forced ...   
1     \nThe war for Eternia begins again in what may...   
2     \nSheriff Deputy Rick Grimes wakes up from a c...   
3     \nAn animated series that follows the exploits...   
4     \nA prequel, set before the events of Army of ...   
...                                                 ...   
9994                                     \nAdd a Plot\n   
9995                                     \nAdd a Plot\n   
9996                                     \nAdd a Plot\n   
9997                                     \nAdd a Plot\n   
9998                                     \nAdd a Plot\n   

                                                  STARS    VOTES RunTime Gross  
0     \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062   121.0   NaN  
1     \n            \n    Stars:\nChris Wood, \nSara...   17,870    25.0   NaN  
2     \n            \n    Stars:\nAndrew Lincoln, \n...  885,805    44.0   NaN  
3     \n            \n    Stars:\nJustin Roiland, \n...  414,849    23.0   NaN  
4     \n    Director:\nMatthias Schweighöfer\n| \n  ...      NaN      80   NaN  
...                                                 ...      ...     ...   ...  
9994  \n            \n    Stars:\nMorgan Taylor Camp...      NaN      80   NaN  
9995                                                 \n      NaN      80   NaN  
9996  \n    Director:\nOrlando von Einsiedel\n| \n  ...      NaN      80   NaN  
9997  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      80   NaN  
9998  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      80   NaN  

[9999 rows x 9 columns]

In [137]:
movie['GENRE'].value_counts()


GENRE
[Comedy]                          852
[Animation, Action, Adventure]    693
[Drama]                           562
[Documentary]                     498
[Crime, Drama, Mystery]           336
                                 ... 
[Horror, Romance]                   1
[Drama, Sci-Fi, War]                1
[Documentary, Action, History]      1
[Documentary, Biography, War]       1
[Adventure, Music, Sci-Fi]          1
Name: count, Length: 511, dtype: int64

In [138]:
movie.isnull()

MOVIES   YEAR  GENRE  RATING  ONE-LINE  STARS  VOTES  RunTime  \
0      False  False  False   False     False  False  False    False   
1      False  False  False   False     False  False  False    False   
2      False  False  False   False     False  False  False    False   
3      False  False  False   False     False  False  False    False   
4      False  False  False   False     False  False   True    False   
...      ...    ...    ...     ...       ...    ...    ...      ...   
9994   False  False  False   False     False  False   True    False   
9995   False  False  False   False     False  False   True    False   
9996   False  False  False   False     False  False   True    False   
9997   False  False  False   False     False  False   True    False   
9998   False  False  False   False     False  False   True    False   

      Movie_name   tags  
0          False  False  
1          False  False  
2          False  False  
3          False  False  
4          False  False  
...          ...    ...  
9994       False  False  
9995       False  False  
9996       False  False  
9997       False  False  
9998       False  False  

[9999 rows x 10 columns]

#Checking how many **null** values are present in each **feature**

In [98]:
missing_values_count = movie.isnull().sum()
print(missing_values_count)

MOVIES         0
YEAR         644
GENRE         80
RATING         0
ONE-LINE       0
STARS          0
VOTES       1820
RunTime        0
Gross       9539
dtype: int64


#**GROSS** has too many Null Values so better **DROP** it

In [100]:
movie = movie.drop(columns=['Gross'])

#Modification of RunTime feature

In [99]:
movie.loc[movie['GENRE'] == 'Comedy', 'VOTES'] = movie.loc[movie['GENRE'] == 'Comedy', 'VOTES'].fillna(1200)
movie.loc[movie['GENRE'] == 'Thriller', 'VOTES'] = movie.loc[movie['GENRE'] == 'Thriller', 'VOTES'].fillna(1800)
movie.loc[movie['GENRE'] == 'Action', 'VOTES'] = movie.loc[movie['GENRE'] == 'Action', 'VOTES'].fillna(1600)
#didNotReallyWorked...

In [101]:
movie

MOVIES         YEAR  \
0                           Blood Red Sky       (2021)   
1     Masters of the Universe: Revelation     (2021– )   
2                        The Walking Dead  (2010–2022)   
3                          Rick and Morty     (2013– )   
4                         Army of Thieves       (2021)   
...                                   ...          ...   
9994                       The Imperfects     (2021– )   
9995                               Arcane     (2021– )   
9996                    Heart of Invictus     (2022– )   
9997                       The Imperfects     (2021– )   
9998                       The Imperfects     (2021– )   

                             GENRE RATING  \
0         Action, Horror, Thriller    6.1   
1     Animation, Action, Adventure    5.0   
2          Drama, Horror, Thriller    8.2   
3     Animation, Adventure, Comedy    9.2   
4            Action, Crime, Horror    7.2   
...                            ...    ...   
9994     Adventure, Drama, Fantasy    7.2   
9995  Animation, Action, Adventure    7.2   
9996            Documentary, Sport    7.2   
9997     Adventure, Drama, Fantasy    7.2   
9998     Adventure, Drama, Fantasy    7.2   

                                               ONE-LINE  \
0     \nA woman with a mysterious illness is forced ...   
1     \nThe war for Eternia begins again in what may...   
2     \nSheriff Deputy Rick Grimes wakes up from a c...   
3     \nAn animated series that follows the exploits...   
4     \nA prequel, set before the events of Army of ...   
...                                                 ...   
9994                                     \nAdd a Plot\n   
9995                                     \nAdd a Plot\n   
9996                                     \nAdd a Plot\n   
9997                                     \nAdd a Plot\n   
9998                                     \nAdd a Plot\n   

                                                  STARS    VOTES RunTime  
0     \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062   121.0  
1     \n            \n    Stars:\nChris Wood, \nSara...   17,870    25.0  
2     \n            \n    Stars:\nAndrew Lincoln, \n...  885,805    44.0  
3     \n            \n    Stars:\nJustin Roiland, \n...  414,849    23.0  
4     \n    Director:\nMatthias Schweighöfer\n| \n  ...      NaN      80  
...                                                 ...      ...     ...  
9994  \n            \n    Stars:\nMorgan Taylor Camp...      NaN      80  
9995                                                 \n      NaN      80  
9996  \n    Director:\nOrlando von Einsiedel\n| \n  ...      NaN      80  
9997  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      80  
9998  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      80  

[9999 rows x 8 columns]

In [102]:
def Convert(string):
    if isinstance(string, str):
        return string.split(",")
    return []

In [103]:
#def Convert(string):
#    li = (string.split(","))
#    return li
movie['GENRE']=movie['GENRE'].apply(Convert)
movie['GENRE']

0           [Action,  Horror,  Thriller]
1       [Animation,  Action,  Adventure]
2            [Drama,  Horror,  Thriller]
3       [Animation,  Adventure,  Comedy]
4              [Action,  Crime,  Horror]
                      ...               
9994       [Adventure,  Drama,  Fantasy]
9995    [Animation,  Action,  Adventure]
9996               [Documentary,  Sport]
9997       [Adventure,  Drama,  Fantasy]
9998       [Adventure,  Drama,  Fantasy]
Name: GENRE, Length: 9999, dtype: object

In [104]:
movie['GENRE']=movie['GENRE'].apply(lambda x:[i.replace(" ","") for i in x])

In [105]:
movie

MOVIES         YEAR  \
0                           Blood Red Sky       (2021)   
1     Masters of the Universe: Revelation     (2021– )   
2                        The Walking Dead  (2010–2022)   
3                          Rick and Morty     (2013– )   
4                         Army of Thieves       (2021)   
...                                   ...          ...   
9994                       The Imperfects     (2021– )   
9995                               Arcane     (2021– )   
9996                    Heart of Invictus     (2022– )   
9997                       The Imperfects     (2021– )   
9998                       The Imperfects     (2021– )   

                               GENRE RATING  \
0         [Action, Horror, Thriller]    6.1   
1     [Animation, Action, Adventure]    5.0   
2          [Drama, Horror, Thriller]    8.2   
3     [Animation, Adventure, Comedy]    9.2   
4            [Action, Crime, Horror]    7.2   
...                              ...    ...   
9994     [Adventure, Drama, Fantasy]    7.2   
9995  [Animation, Action, Adventure]    7.2   
9996            [Documentary, Sport]    7.2   
9997     [Adventure, Drama, Fantasy]    7.2   
9998     [Adventure, Drama, Fantasy]    7.2   

                                               ONE-LINE  \
0     \nA woman with a mysterious illness is forced ...   
1     \nThe war for Eternia begins again in what may...   
2     \nSheriff Deputy Rick Grimes wakes up from a c...   
3     \nAn animated series that follows the exploits...   
4     \nA prequel, set before the events of Army of ...   
...                                                 ...   
9994                                     \nAdd a Plot\n   
9995                                     \nAdd a Plot\n   
9996                                     \nAdd a Plot\n   
9997                                     \nAdd a Plot\n   
9998                                     \nAdd a Plot\n   

                                                  STARS    VOTES RunTime  
0     \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062   121.0  
1     \n            \n    Stars:\nChris Wood, \nSara...   17,870    25.0  
2     \n            \n    Stars:\nAndrew Lincoln, \n...  885,805    44.0  
3     \n            \n    Stars:\nJustin Roiland, \n...  414,849    23.0  
4     \n    Director:\nMatthias Schweighöfer\n| \n  ...      NaN      80  
...                                                 ...      ...     ...  
9994  \n            \n    Stars:\nMorgan Taylor Camp...      NaN      80  
9995                                                 \n      NaN      80  
9996  \n    Director:\nOrlando von Einsiedel\n| \n  ...      NaN      80  
9997  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      80  
9998  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      80  

[9999 rows x 8 columns]

Making list of all other features too so that tags can be generated

In [106]:
movie['ONE-LINE']=movie['ONE-LINE'].apply(Convert)
movie['STARS']=movie['STARS'].apply(Convert)
movie['YEAR']=movie['YEAR'].apply(Convert)
movie['RunTime']=movie['RunTime'].apply(Convert)
movie['RATING']=movie['RATING'].apply(Convert)

In [107]:
movie

MOVIES           YEAR  \
0                           Blood Red Sky       [(2021)]   
1     Masters of the Universe: Revelation     [(2021– )]   
2                        The Walking Dead  [(2010–2022)]   
3                          Rick and Morty     [(2013– )]   
4                         Army of Thieves       [(2021)]   
...                                   ...            ...   
9994                       The Imperfects     [(2021– )]   
9995                               Arcane     [(2021– )]   
9996                    Heart of Invictus     [(2022– )]   
9997                       The Imperfects     [(2021– )]   
9998                       The Imperfects     [(2021– )]   

                               GENRE RATING  \
0         [Action, Horror, Thriller]     []   
1     [Animation, Action, Adventure]     []   
2          [Drama, Horror, Thriller]     []   
3     [Animation, Adventure, Comedy]     []   
4            [Action, Crime, Horror]  [7.2]   
...                              ...    ...   
9994     [Adventure, Drama, Fantasy]  [7.2]   
9995  [Animation, Action, Adventure]  [7.2]   
9996            [Documentary, Sport]  [7.2]   
9997     [Adventure, Drama, Fantasy]  [7.2]   
9998     [Adventure, Drama, Fantasy]  [7.2]   

                                               ONE-LINE  \
0     [\nA woman with a mysterious illness is forced...   
1     [\nThe war for Eternia begins again in what ma...   
2     [\nSheriff Deputy Rick Grimes wakes up from a ...   
3     [\nAn animated series that follows the exploit...   
4     [\nA prequel,  set before the events of Army o...   
...                                                 ...   
9994                                   [\nAdd a Plot\n]   
9995                                   [\nAdd a Plot\n]   
9996                                   [\nAdd a Plot\n]   
9997                                   [\nAdd a Plot\n]   
9998                                   [\nAdd a Plot\n]   

                                                  STARS    VOTES RunTime  
0     [\n    Director:\nPeter Thorwarth\n| \n    Sta...   21,062      []  
1     [\n            \n    Stars:\nChris Wood,  \nSa...   17,870      []  
2     [\n            \n    Stars:\nAndrew Lincoln,  ...  885,805      []  
3     [\n            \n    Stars:\nJustin Roiland,  ...  414,849      []  
4     [\n    Director:\nMatthias Schweighöfer\n| \n ...      NaN    [80]  
...                                                 ...      ...     ...  
9994  [\n            \n    Stars:\nMorgan Taylor Cam...      NaN    [80]  
9995                                               [\n]      NaN    [80]  
9996  [\n    Director:\nOrlando von Einsiedel\n| \n ...      NaN    [80]  
9997  [\n    Director:\nJovanka Vuckovic\n| \n    St...      NaN    [80]  
9998  [\n    Director:\nJovanka Vuckovic\n| \n    St...      NaN    [80]  

[9999 rows x 8 columns]

left the **VOTES** features as too much nulls

In [108]:
movie['Movie_name'] = movie['MOVIES']
movie['tags']= movie['GENRE']+movie['RATING']+movie['ONE-LINE']+movie['STARS']+movie['RunTime']

In [109]:
movie

MOVIES           YEAR  \
0                           Blood Red Sky       [(2021)]   
1     Masters of the Universe: Revelation     [(2021– )]   
2                        The Walking Dead  [(2010–2022)]   
3                          Rick and Morty     [(2013– )]   
4                         Army of Thieves       [(2021)]   
...                                   ...            ...   
9994                       The Imperfects     [(2021– )]   
9995                               Arcane     [(2021– )]   
9996                    Heart of Invictus     [(2022– )]   
9997                       The Imperfects     [(2021– )]   
9998                       The Imperfects     [(2021– )]   

                               GENRE RATING  \
0         [Action, Horror, Thriller]     []   
1     [Animation, Action, Adventure]     []   
2          [Drama, Horror, Thriller]     []   
3     [Animation, Adventure, Comedy]     []   
4            [Action, Crime, Horror]  [7.2]   
...                              ...    ...   
9994     [Adventure, Drama, Fantasy]  [7.2]   
9995  [Animation, Action, Adventure]  [7.2]   
9996            [Documentary, Sport]  [7.2]   
9997     [Adventure, Drama, Fantasy]  [7.2]   
9998     [Adventure, Drama, Fantasy]  [7.2]   

                                               ONE-LINE  \
0     [\nA woman with a mysterious illness is forced...   
1     [\nThe war for Eternia begins again in what ma...   
2     [\nSheriff Deputy Rick Grimes wakes up from a ...   
3     [\nAn animated series that follows the exploit...   
4     [\nA prequel,  set before the events of Army o...   
...                                                 ...   
9994                                   [\nAdd a Plot\n]   
9995                                   [\nAdd a Plot\n]   
9996                                   [\nAdd a Plot\n]   
9997                                   [\nAdd a Plot\n]   
9998                                   [\nAdd a Plot\n]   

                                                  STARS    VOTES RunTime  \
0     [\n    Director:\nPeter Thorwarth\n| \n    Sta...   21,062      []   
1     [\n            \n    Stars:\nChris Wood,  \nSa...   17,870      []   
2     [\n            \n    Stars:\nAndrew Lincoln,  ...  885,805      []   
3     [\n            \n    Stars:\nJustin Roiland,  ...  414,849      []   
4     [\n    Director:\nMatthias Schweighöfer\n| \n ...      NaN    [80]   
...                                                 ...      ...     ...   
9994  [\n            \n    Stars:\nMorgan Taylor Cam...      NaN    [80]   
9995                                               [\n]      NaN    [80]   
9996  [\n    Director:\nOrlando von Einsiedel\n| \n ...      NaN    [80]   
9997  [\n    Director:\nJovanka Vuckovic\n| \n    St...      NaN    [80]   
9998  [\n    Director:\nJovanka Vuckovic\n| \n    St...      NaN    [80]   

                               Movie_name  \
0                           Blood Red Sky   
1     Masters of the Universe: Revelation   
2                        The Walking Dead   
3                          Rick and Morty   
4                         Army of Thieves   
...                                   ...   
9994                       The Imperfects   
9995                               Arcane   
9996                    Heart of Invictus   
9997                       The Imperfects   
9998                       The Imperfects   

                                                   tags  
0     [Action, Horror, Thriller, \nA woman with a my...  
1     [Animation, Action, Adventure, \nThe war for E...  
2     [Drama, Horror, Thriller, \nSheriff Deputy Ric...  
3     [Animation, Adventure, Comedy, \nAn animated s...  
4     [Action, Crime, Horror, 7.2, \nA prequel,  set...  
...                                                 ...  
9994  [Adventure, Drama, Fantasy, 7.2, \nAdd a Plot\...  
9995  [Animation, Action, Adventure, 7.2, \nAdd a Pl...  
9996  [Documentary, Sport, 7.2, \nAdd a Plot\n, \n  ...  
9997  

In [110]:
new_df=movie[['Movie_name','tags']]
new_df['tags'] =new_df['tags'].apply(lambda x: " ".join(x))
new_df.head()

<ipython-input-110-7ff2b6aac47b>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] =new_df['tags'].apply(lambda x: " ".join(x))


Movie_name  \
0                        Blood Red Sky   
1  Masters of the Universe: Revelation   
2                     The Walking Dead   
3                       Rick and Morty   
4                      Army of Thieves   

                                                tags  
0  Action Horror Thriller \nA woman with a myster...  
1  Animation Action Adventure \nThe war for Etern...  
2  Drama Horror Thriller \nSheriff Deputy Rick Gr...  
3  Animation Adventure Comedy \nAn animated serie...  
4  Action Crime Horror 7.2 \nA prequel  set befor...

In [111]:
def Convert(string):
    li = string.lower()
    return li

In [112]:
new_df['Movie_name']=new_df['Movie_name'].str.lower()

<ipython-input-112-65abc78dc5fb>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Movie_name']=new_df['Movie_name'].str.lower()


In [113]:
new_df

Movie_name  \
0                           blood red sky   
1     masters of the universe: revelation   
2                        the walking dead   
3                          rick and morty   
4                         army of thieves   
...                                   ...   
9994                       the imperfects   
9995                               arcane   
9996                    heart of invictus   
9997                       the imperfects   
9998                       the imperfects   

                                                   tags  
0     Action Horror Thriller \nA woman with a myster...  
1     Animation Action Adventure \nThe war for Etern...  
2     Drama Horror Thriller \nSheriff Deputy Rick Gr...  
3     Animation Adventure Comedy \nAn animated serie...  
4     Action Crime Horror 7.2 \nA prequel  set befor...  
...                                                 ...  
9994  Adventure Drama Fantasy 7.2 \nAdd a Plot\n \n ...  
9995  Animation Action Adventure 7.2 \nAdd a Plot\n ...  
9996  Documentary Sport 7.2 \nAdd a Plot\n \n    Dir...  
9997  Adventure Drama Fantasy 7.2 \nAdd a Plot\n \n ...  
9998  Adventure Drama Fantasy 7.2 \nAdd a Plot\n \n ...  

[9999 rows x 2 columns]

In [114]:

#####Imporint feature extractor################

import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

cv = CountVectorizer(max_features=5000,stop_words='english')
vector = cv.fit_transform(new_df['tags']).toarray()


print(vector)
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem(text):
  y =[]

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)


new_df['tags']=new_df['tags'].apply(stem)
print(new_df)
similarity = cosine_similarity(vector)
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x: x[1])[1:6]
similarity[0]

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


<ipython-input-114-0350125359c4>:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)


                               Movie_name  \
0                           blood red sky   
1     masters of the universe: revelation   
2                        the walking dead   
3                          rick and morty   
4                         army of thieves   
...                                   ...   
9994                       the imperfects   
9995                               arcane   
9996                    heart of invictus   
9997                       the imperfects   
9998                       the imperfects   

                                                   tags  
0     action horror thriller a woman with a mysteri ...  
1     anim action adventur the war for eternia begin...  
2     drama horror thriller sheriff deputi rick grim...  
3     anim adventur comedi an anim seri that follow ...  
4     action crime horror 7.2 a prequel set befor th...  
...                                                 ...  
9994  adventur drama fantasi 7.2 add a plot stars: m.

array([1.        , 0.18181818, 0.1956464 , ..., 0.06428243, 0.12309149,
       0.11396058])

In [115]:
######OUTPUT####
def recommend(movie):
    movie_index = new_df[new_df['Movie_name'] == movie].index[0]
    distances = similarity[movie_index]
    movie = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]
    for i in movie:
        print(new_df.iloc[i[0]].Movie_name)
recommend('the walking dead')

qala
day of the dead: bloodline
slasher
bitten
tabula rasa


In [124]:
recommend('blood red sky')

[(605, 0.3962969619506085), (1944, 0.3818813079129867), (3489, 0.33557802760701216), (1897, 0.32732683535398865), (3400, 0.32274861218395146)]
the bad batch
the mother
johan falk: blodsdiamanter
extraction 2
kabaneri of the iron fortress: unato decisive battle


In [134]:
recommend('The wAlking DeAd'.lower())

[(280, 0.3086066999241838), (4188, 0.2760262237369417), (1360, 0.2727723627949905), (1650, 0.2631806779839076), (938, 0.2618614682831909)]
slasher
qala
day of the dead: bloodline
luna nera
tiny pretty things


In [136]:
recommend('army of thieves')

[(9751, 0.31249999999999994), (7704, 0.29166666666666663), (1765, 0.28347335475692037), (7907, 0.2795084971874737), (8590, 0.2795084971874737)]
 bangkok breaking
 queen sono
the old guard 2
 queen sono
 queen sono


In [116]:

#####Imporint feature extractor################

import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

cv = CountVectorizer(max_features=5000,stop_words='english')
vector = cv.fit_transform(new_df['tags']).toarray()


print(vector)
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem(text):
  y =[]

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)


new_df['tags']=new_df['tags'].apply(stem)
print(new_df)
similarity = cosine_similarity(vector)
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x: x[1])[1:6]
similarity[0]

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


<ipython-input-116-0350125359c4>:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)


                               Movie_name  \
0                           blood red sky   
1     masters of the universe: revelation   
2                        the walking dead   
3                          rick and morty   
4                         army of thieves   
...                                   ...   
9994                       the imperfects   
9995                               arcane   
9996                    heart of invictus   
9997                       the imperfects   
9998                       the imperfects   

                                                   tags  
0     action horror thriller a woman with a mysteri ...  
1     anim action adventur the war for eternia begin...  
2     drama horror thriller sheriff deputi rick grim...  
3     anim adventur comedi an anim seri that follow ...  
4     action crime horror 7.2 a prequel set befor th...  
...                                                 ...  
9994  adventur drama fantasi 7.2 add a plot stars: m.

array([1.        , 0.16666667, 0.17817416, ..., 0.06154575, 0.11785113,
       0.10910895])

In [117]:
new_df.iloc[3].name

3

In [118]:
#import pickle

In [119]:
#new_df=pickle.load(open("/content/drive/MyDrive/new_model.pkl","rb"))
#similarity = pickle.load(open("/content/drive/MyDrive/similarity.pkl","rb"))

In [120]:
#new_food = pickle.dump(new_df,open("/content/drive/MyDrive/new_model.pkl",'wb'))
#new_food = pickle.dump(similarity,open("/content/drive/MyDrive/similarity.pkl",'wb'))


In [139]:
def recommend(movie):
    movie_index = new_df[new_df['Movie_name'] == movie].index[0]
    distances = similarity[movie_index]
    movie = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]
    print(movie)
    for i in movie:
        print(new_df.iloc[i[0]].Movie_name)

recommend('rick and morty')
#why is it showing all same output for this movie??

[(7310, 0.5969620057957092), (7309, 0.565752381856018), (7302, 0.5195887333176439), (7303, 0.5146749286021822), (7305, 0.5060243137049899)]
 rick and morty
 rick and morty
 rick and morty
 rick and morty
 rick and morty


In [140]:
recommend('the imperfects')
#why four same and just one different output?

[(9997, 0.5669467095138407), (9935, 0.5447047794019222), (9994, 0.5447047794019222), (9998, 0.5248906591678238), (3230, 0.3086066999241838)]
 the imperfects
 the imperfects
 the imperfects
 the imperfects
the three-body problem


In [141]:
recommend('titanic')
#for movies not on dataset, it doesnot work?!

IndexError: index 0 is out of bounds for axis 0 with size 0